version: '3'

services:
  devgrid-api:
    build: .
    container_name: devgrid-api
    volumes:
      - ./src:/app/src
    ports:
      - '3333:3333'
    networks:
      - devgrid-network
    links:
      - redis

  redis:
    container_name: devgrid-redis
    image: redis
    ports:
      - "6381:6379"

networks:
  devgrid-network:
    driver: bridge
